version: "3"
services:
    db:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        container_name: "mongohost"
        ports:
            - "27017:27017"
        volumes:
            - "./datadir:/data/db"
        networks:
            - "mongo-network"

networks:
    "mongo-network":
        driver: "bridge"

